@echo off
echo Setting DB_CLIENT...
call npx vercel env add DB_CLIENT production --value mysql --yes --force < NUL
echo Setting DB_HOST...
call npx vercel env add DB_HOST production --value gateway01.ap-southeast-1.prod.alicloud.tidbcloud.com --yes --force < NUL
echo Setting DB_PORT...
call npx vercel env add DB_PORT production --value 4000 --yes --force < NUL
echo Setting DB_USER...
call npx vercel env add DB_USER production --value eFB3KMf2qdor1dt.root --yes --force < NUL
echo Setting DB_PASSWORD...
call npx vercel env add DB_PASSWORD production --value dZzUtLyDt3dIcTvP --yes --force < NUL
echo Setting DB_NAME...
call npx vercel env add DB_NAME production --value cargo_warehouse --yes --force < NUL
echo Setting JWT_SECRET...
call npx vercel env add JWT_SECRET production --value dZzUtLyDt3dIcTvP-secure-jwt-key-2026 --yes --force < NUL
echo Setting JWT_EXPIRES_IN...
call npx vercel env add JWT_EXPIRES_IN production --value 7d --yes --force < NUL
echo Setting NODE_ENV...
call npx vercel env add NODE_ENV production --value production --yes --force < NUL
echo All env variables set successfully!
